### ISSUE TITLE
Event for unknown address

### ISSUE THREAD

**Issue by swesley** [insum-labs/apex-plugin-google-places-autocomplete#12]
If the user finds a valid address, then modifies the address to something that does not exist - how do we capture this event so that we can clear the underlying fields?

It seems the place_changed event does not fire, so I'm unable to test the length of this.data

**Comment by neilfernandez** [comment]
Could you please re-import the plugin with the latest version?
The place_changed event should be firing in the last release.

As for catching if someone changes the address to something that does not exist to clear the underlying value. I believe custom JS would be the best route. Detecting when place_changed returns data, then storing that, and checking if the input does not match that after. 

Something along the lines of this if that makes sense.

**Comment by swesley** [comment]
My original download was dated 9th Feb, and I don't see any changes since then.

I mean it does not fire when you type a free form address and ignore the autocomplete.

A regular onChange event fires in both circumstances, so I could probably use your suggestion of storing the address input for comparison to solve this.
edit - it still fires first. I'm comparing current search with previous search, and returns true in both circumstances (free-form & autocomplete). So I'm still unable to distinguish freeform entry.

Question posted https://community.oracle.com/message/14786805
