### ISSUE TITLE
Lat and Long not saving to DB

### ISSUE THREAD

**Issue by nvanscha** [insum-labs/apex-plugin-google-places-autocomplete#14]
I'm using this plugin within the Interactive Grid. All fields save successfully, except the latitude and longitude. It autopopulates perfectly, but the moment I press save, it clear those 2 fields and does not save it do the db.
Am I doing something wrong?
Niel.

**Comment by neilfernandez** [comment]
Hi Niel,

You are not doing anything wrong. This is a bug. Thank you for pointing this out. Will fix it in the next release.

Best,
Neil
