### ISSUE TITLE
Save lat & long to item in german is not a number

### ISSUE THREAD

**Issue by RonnyWeiss** [insum-labs/apex-plugin-google-places-autocomplete#15]
Hello

Thank you for the great plug-in. 

But there's a bug when using apex in german and storing the values on a number item than lat and lot is sotred with a dot and not with comma as decimal seperator.

Here is the Code we have changed after line 138:

                var lat = uiw._values.place.geometry.location.lat();
                var long = uiw._values.place.geometry.location.lng();

                if (apex.locale.getDecimalSeparator() == ',') {
                    lat = lat.toString().replace(/\./g, ',');
                    long = long.toString().replace(/\./g, ',');
                }

                // Set latitude and longitude if they exist
                uiw.options.pageItems.lat.id ? $s(uiw.options.pageItems.lat.id, lat) : null;
                uiw.options.pageItems.lng.id ? $s(uiw.options.pageItems.lng.id, long) : null;

We would please you to fix this in next version.

And could you please update the version in plug-in. In Github there exists a version 1.0.4 and in plug-in there only a 1.0?

Thank you! 

kind regards

Ronny

**Comment by BernhardFW** [comment]
despite having added Ronnies code as above - its not working for me either... Germany - even in the autocomplete item nothing is happening... 
for which type of google-maps product (maps, route, location (I choose location) has the API-key to work ?
Thks
Bernhard
