### ISSUE TITLE
The item is not render properly at all with v 18.1 -an unexpected internal application error

### ISSUE THREAD

**Issue by AmrAbdeen** [insum-labs/apex-plugin-google-places-autocomplete#17]
Hi,

First thanks for the great plugin.

But I met this error after installed it,
Please, Help

--- 

> an unexpected internal application error has occurred and recorded in our log so please get in contact with the support team for further investigation.
> Technical Info (only visible for developers)
> is_internal_error: true
> apex_error_code: WWV_FLOW_PLUGIN.RUN_PLSQL_ERR
> original message: Error in PLSQL code raised during plug-in processing.
> original_additional_info: Contact your application administrator.
> ora_sqlcode: -6550
> ora_sqlerrm: ORA-06550: line 34, column 57: PLS-00302: component 'C_COMP_TYPE_IG_COLUMN' must be declared ORA-06512: at "APEX_190100.WWV_FLOW_DYNAMIC_EXEC", line 1500 ORA-06512: at "APEX_190100.WWV_FLOW_DYNAMIC_EXEC", line 2501 ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_190100", line 533 ORA-06550: line 34, column 27: PL/SQL: Item ignored ORA-06550: line 35, column 57: PLS-00302: component 'C_COMP_TYPE_PAGE_ITEM' must be declared ORA-06550: line 35, column 27: PL/SQL: Item ignored ORA-06550: line 120, column 130: PLS-00320: the declaration of the type of this expression is incomplete or malformed ORA-06550: line 120, column 5: PL/SQL: Statement ignored ORA-06550: line 121, column 130: PLS-00320: the declaration of the type of this expression is incomplete or malformed ORA-06550: line 121, column 5: PL/SQL: Statement ignored ORA-06512: at "SYS.DBMS_SYS_SQL", line 1458 ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_190100", line 522 ORA-06512: at "APEX_190100.WWV_FLOW_DYNAMIC_EXEC", line 1982 ORA-06512: at "APEX_190100.WWV_FLOW_DYNAMIC_EXEC", line 2467 ORA-06512: at "APEX_190100.WWV_FLOW_DYNAMIC_EXEC", line 1476
> component.type: APEX_APPLICATION_PAGE_ITEMS
> component.id: 231431254677907002
> component.name: P3_LOCATION
> error_backtrace:
> ORA-06512: at "SYS.DBMS_SYS_SQL", line 1458
> ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_190100", line 522
> ORA-06512: at "APEX_190100.WWV_FLOW_DYNAMIC_EXEC", line 1500
> ORA-06512: at "APEX_190100.WWV_FLOW_DYNAMIC_EXEC", line 2501
> ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_190100", line 533
> ORA-06512: at "SYS.DBMS_SYS_SQL", line 1458
> ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_190100", line 522
> ORA-06512: at "APEX_190100.WWV_FLOW_DYNAMIC_EXEC", line 1982
> ORA-06512: at "APEX_190100.WWV_FLOW_DYNAMIC_EXEC", line 2467
> ORA-06512: at "APEX_190100.WWV_FLOW_DYNAMIC_EXEC", line 1476
> ORA-06512: at "APEX_190100.WWV_FLOW_PLUGIN", line 1334
> error_statement:
> begin declare
> procedure render_autocomplete  (
>     p_item in apex_plugin.t_item,
>     p_plugin in apex_plugin.t_plugin,
>     p_param in apex_plugin.t_item_render_param,
>     p_result in out nocopy apex_plugin.t_item_render_result ) IS
> 
>     subtype plugin_attr is varchar2(32767);
> 
>     l_result apex_plugin.t_item_render_result;
>     l_js_params varchar2(1000);
>     l_onload_string varchar2(32767);
> 
>     -- Plugin attributes
>     l_api_key plugin_attr := p_plugin.attribute_01;
> 
>     -- Component attributes
>     l_action plugin_attr := p_item.attribute_01;
>     l_address plugin_attr := p_item.attribute_02;
>     l_city plugin_attr := p_item.attribute_03;
>     l_state plugin_attr := p_item.attribute_04;
>     l_zip plugin_attr := p_item.attribute_05;
>     l_country plugin_attr := p_item.attribute_06;
>     l_latitude plugin_attr := p_item.attribute_07;
>     l_longitude plugin_attr := p_item.attribute_08;
>     l_address_long plugin_attr := p_item.attribute_09;
>     l_state_long plugin_attr := p_item.attribute_10;
>     l_country_long plugin_attr := p_item.attribute_11;
>     l_location_type plugin_attr := p_item.attribute_12;
>     l_location_bias plugin_attr := p_item.attribute_13;
> 
>     -- Component type
>     l_component_type plugin_attr := p_item.component_type_id;
>     l_comp_type_ig_column plugin_attr := apex_component.c_comp_type_ig_column;
>     l_comp_type_page_item plugin_attr := apex_component.c_comp_type_page_item;
>     
>     c_name constant varchar2(30) := apex_plugin.get_input_name_for_item;
> 
> begin
> 
>     -- Get API key for JS file name
>     l_js_params := '?key=' || l_api_key || '&libraries=places';
> 
>     apex_javascript.add_library
>           (p_name           => 'js' || l_js_params
>           ,p_directory      => 'https://maps.googleapis.com/maps/api/'
>           ,p_skip_extension => true);
> 
>     apex_javascript.add_library
>       (p_name                  => 'jquery.ui.autoComplete'
>       ,p_directory             => p_plugin.file_prefix);
> 
>     -- For use with APEX 5.1 and up. Print input element.
>     sys.htp.prn (apex_string.format('<input type="text" %s size="%s" maxlength="%s"/>'
>                                     , apex_plugin_util.get_element_attributes(p_item, c_name, 'text_field')
>                                     , p_item.element_width
>                                     , p_item.element_max_length));
> 
> l_onload_string :=
> '
> $("#%NAME%").placesAutocomplete({
>   pageItems : {
>     autoComplete : {
>       %AUTOCOMPLETE_ID%
>       %PAGE_ITEM_VALUE%
>     },
>     lat : {
>       %LAT_ID%
>     },
>     lng : {
>       %LNG_ID%
>     },
>     route : {
>       %ROUTE_ID%
>       %ROUTE_FORM%
>     },
>     locality : {
>       %LOCALITY_ID%
>       %LOCALITY_FORM%
>     },
>     administrative_area_level_1 : {
>       %ADMINISTRATIVE_AREA_LEVEL_1_ID%
>       %ADMINISTRATIVE_AREA_LEVEL_1_FORM%
>     },
>     postal_code : {
>       %POSTAL_CODE_ID%
>       %POSTAL_CODE_FORM%
>     },
>     country : {
>       %COUNTRY_ID%
>       %COUNTRY_FORM%
>     }
>   },
>   %ACTION%
>   %TYPE%
>   %COMP_TYPE%
>   %COMP_TYPE_PAGE_ITEM%
>   %COMP_TYPE_IG_COLUMN%
>   %LOCATION_BIAS%
> });
> ';
>     l_onload_string := replace(l_onload_string,'%NAME%',p_item.name);
>     l_onload_string := replace(l_onload_string, '%AUTOCOMPLETE_ID%', apex_javascript.add_attribute('id',  p_item.name));
>     l_onload_string := replace(l_onload_string, '%PAGE_ITEM_VALUE%', apex_javascript.add_attribute('page_item_value',  V(p_item.attribute_02)));
>     l_onload_string := replace(l_onload_string, '%ROUTE_ID%', apex_javascript.add_attribute('id',  l_address));
>     l_onload_string := replace(l_onload_string, '%ROUTE_FORM%', apex_javascript.add_attribute('form',  case when l_address_long = 'Y' then 'long_name' else 'short_name' end));
>     l_onload_string := replace(l_onload_string, '%LOCALITY_ID%', apex_javascript.add_attribute('id',  l_city));
>     l_onload_string := replace(l_onload_string, '%LOCALITY_FORM%', apex_javascript.add_attribute('form',  'long_name'));
>     l_onload_string := replace(l_onload_string, '%ADMINISTRATIVE_AREA_LEVEL_1_ID%', apex_javascript.add_attribut
> 

---

**Comment by neilfernandez** [comment]
What version of APEX are you on?

**Comment by neilfernandez** [comment]
Please download the latest version of the app, and put a valid API key. I just tested on a fresh app on 18.1, and can not reproduce the issue.

**Comment by jeffreykemp** [comment]
It looks like you're on APEX 19.1, not 18.1, given your apex error indicates the error is being raised from the schema `APEX_190100`. It's complaining about the plugin lines referencing constants in `apex_component`, which it shouldn't if the installation is stable. If the problem persists I'd suspect an issue with your APEX installation. Re-installing it might be needed.
