### ISSUE TITLE
Compatibility for Apex 19.x

### ISSUE THREAD

**Issue by heno-dave** [insum-labs/apex-plugin-google-places-autocomplete#18]
Hi, this plugin is not working with Apex version 19.1.x. Looking at the apexplugin.json file, the Oracle and Apex versions listed stop at 18.1 and 18.2 respectively. 
Are there plans to revamp this plugin for version 19? Thanks~

**Comment by heno-dave** [comment]
False alarm! I did not have the maps.googleapis.com URL in the ACL, and wasn't using the plug-in Item correctly. Works on version 19.1 just fine. Thanks for the plug-in!

**Comment by neilfernandez** [comment]
Glad to hear it works!
