### ISSUE TITLE
It doesn't works for me

### ISSUE THREAD

**Issue by Frankf1203** [insum-labs/apex-plugin-google-places-autocomplete#19]
I don't know if I'm doing something wrong. But I did every step as the instructions said, but it gives me and error. That errors happens seconds after the page loads. And when I try typing something it won't let me after 3 leters type. I'm actually running it on Apex 19.1.
![Annotation 2019-08-29 210127](https://user-images.githubusercontent.com/39652031/63990189-561f9800-caa0-11e9-91b2-571077bf5e10.jpg)

**Comment by neilfernandez** [comment]
What is the error?

**Comment by Frankf1203** [comment]
[Image]
Well when I try to type a direction it tells this.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by neilfernandez** [comment]
Still can not see the photo. Need you to either send the photo through GitHub via uploading it or a copy of the text.
