### ISSUE TITLE
1 error has occurred NOT COMPATIBLE (Your export may contain calls not supported by your application version.)

### ISSUE THREAD

**Issue by adambadge** [insum-labs/apex-plugin-google-places-autocomplete#23]
I am trying to install this plugin via Oracle Application Express import plugin prompt as an admin user and getting the below error:
"1 error has occurred NOT COMPATIBLE (Your export may contain calls not supported by your application version.)"

APEX config is as follows:

Product Build | 19.2.0.00.18
Schema Compatibility | 2019.10.04
Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production

Any help would be greatly appreciated

**Comment by adambadge** [comment]
Okay found the error of my ways, my version is too old now. I used commit - 653eeabf2816d136110cb01bfbba2d4c980ac35d and that fixed my issue.

**Comment by neilfernandez** [comment]
Nice. Did you try installing from the latest release? It should contain that commit.

https://github.com/insum-labs/apex-plugin-google-places-autocomplete/releases/tag/1.2.1

Please let me know. If you downloaded 1.2.1 and that caused the issue then something needs to be fixed.

**Comment by adambadge** [comment]
@neilfernandez Thanks for the prompt follow-up and the great tool. I'll give 1.2.1 a test and let you know. Many thanks.

**Comment by adambadge** [comment]
@neilfernandez I have just attempted to install 1.2.1 plugin and I am getting the error:
 "1 error has occurred NOT COMPATIBLE (Your export may contain calls not supported by your application version.)"

My version of APEX is currently - Application Express 19.2.0.00.18

If I use an older commit it works.

**Comment by jeffreykemp** [comment]
I can see the 1.2.1 tag is for APEX 20.1.0.00.13 so it is expected to get that error on 19.2.

**Comment by neilfernandez** [comment]
Thank you @jeffreykemp. He is right. I will figure this out 👍. For the time being, please use an older release until fixed.

**Comment by neilfernandez** [comment]
Migrating this to #24. Will be taken care of in there.

**Comment by neilfernandez** [comment]
@jeffreykemp : I noticed in your maps plugin you backport. I modify the export file to do so, curious if you have a better or another method?

**Comment by jeffreykemp** [comment]
In order to ensure support I backport manually - I maintain an older version in 5.0 that I re-implement changes to. It can be a bit laborious but the changes are mostly in the PL/SQL and javascript which is easy to copy in.

**Comment by neilfernandez** [comment]
@adambadge Please download release [1.2.2](https://github.com/insum-labs/apex-plugin-google-places-autocomplete/releases/tag/1.2.2) Should work for 5.1 now.
