### ISSUE TITLE
Older APEX versions not supported

### ISSUE THREAD

**Issue by jeffreykemp** [insum-labs/apex-plugin-google-places-autocomplete#24]
The `apexplugin.json` file indicates that the plugin is supported as far back as 5.1:

    "versions" : ["5.1.0","18.1.0", "18.2.0", "19.0.0", "19.1.0", "20.1.0"],

But the latest versions of the plugin (including master and tag 1.2.1) will only support 20.1.

**Comment by neilfernandez** [comment]
With the upgrade of apex.oracle.com my plugin is now compatible with 20.1. Only thing I recall doing recently was exporting it from 20.1 and I must have assumed it was still backwards compatible. Thanks for catching this. I need to look into my options. If needed for older versions please use an older release until I fix this.

**Comment by neilfernandez** [comment]
Please download release [1.2.2](https://github.com/insum-labs/apex-plugin-google-places-autocomplete/releases/tag/1.2.2). Should work for 5.1 now.
