### ISSUE TITLE
Add option to turn geolocate on and off

### ISSUE THREAD

**Issue by neilfernandez** [insum-labs/apex-plugin-google-places-autocomplete#3]
The plugin should have a checkbox that turns geolocate on or off rather than always having it on.

**Comment by swesley** [comment]
Always on? I don't feel a bias is present as I'm still getting plenty of results from other countries.

I tried forcing the issue with the location/radius/strictbounds parameters, but I'm not sure they were honoured
https://community.oracle.com/thread/4132005
