### ISSUE TITLE
 error occurred while executing

### ISSUE THREAD

**Issue by gabrielbentoasinc** [insum-labs/apex-plugin-google-places-autocomplete#7]
Good morning, how are you?

Seeing the plugins tab on the Apex World site I was very interested in the autocomplete plugin, I downloaded and installed. I also saw on the github website your explanation for the installation ... I followed everything the way it did, and it is giving error, can you help me?

Some images about the error and the configuration of the field are attached.

![image](https://user-images.githubusercontent.com/36301645/36030821-ce2503fa-0d8f-11e8-9bd0-a1e2d396bd9e.png)
![image](https://user-images.githubusercontent.com/36301645/36030839-de2ed4ce-0d8f-11e8-8c14-ab5569aa73d4.png)
![image](https://user-images.githubusercontent.com/36301645/36030863-f37ac1f8-0d8f-11e8-8225-f079c099fceb.png)
![image](https://user-images.githubusercontent.com/36301645/36030914-2748bdfa-0d90-11e8-8968-8a416a99f64b.png)

**Comment by neilfernandez** [comment]
This was the image sent to be by Gabriel. 

![image](https://user-images.githubusercontent.com/9313239/36033229-63f7343c-0d7e-11e8-9e65-4db76806b174.png)

The API key is invalid. Please get an API Key for the Google Maps Javascript API or the Google Places Javascript API. They both use the same javascript library.

https://developers.google.com/maps/documentation/javascript/get-api-key

https://developers.google.com/places/javascript/

Or go to your developer console and do it from there, then get credentials:
https://console.developers.google.com/apis/

All of these methods work to get a valid API key.
