### ISSUE TITLE
I get Oops! Something went wrong.

### ISSUE THREAD

**Issue by jrdad1** [insum-labs/apex-plugin-google-places-autocomplete#9]
I am using the plugin on a form

![image](https://user-images.githubusercontent.com/11945723/36867815-5ac452dc-1d64-11e8-929a-f4a455f55a2f.png)

I do not use JSON, I split the fields to street address, city, state, zip and country.

I look at the console and I see this.
![image](https://user-images.githubusercontent.com/11945723/36867893-a1a2166c-1d64-11e8-97f6-52d00e5b1cf1.png)

**Comment by neilfernandez** [comment]
This error most likely means that you have an invalid Google Maps API key. 

Please refer to issue #7 for the solution.

Cheers,
Neil
